### ISSUE TITLE
Code Review - Tom

### ISSUE THREAD

**Issue by th0mazth0maz** [MeRichard123/oop-assement-one-UoL#11]
<h3>Positive Points 😊 </h3>
<ul>
<li>Included documentation is detailed and thorough on the code's functionality.</li>
<li>Code is well commented, with comments being relevant and avoiding repetition of points made in the documentation.</li>
<li>The code runs smoothly, with no errors encountered while using the program.</li>
<li>The code layout is well-structured and easy to understand.</li>
<li>Clear method and variable names have been implemented throughout the code, making it easy to understand.</li>
</ul>

<h3>Points of Improvement 😳 </h3>
<ul>
<li>Removing 'Utils.cs' could further improve the code layout, as this code section does not benefit the program's functionality.</li>
<li>Code testing could be improved if methods in 'PackTest.cs' were abstracted.</li>
<li>Ensuring all methods in 'PackTest.cs' are run through and executed in the console would greatly improve testing and ensure all methods function correctly. 
</ul>
<p>LGTM</p>

**Comment by MeRichard123** [comment]
👍
